### ISSUE TITLE
Keeps on running hashcat -I

### ISSUE THREAD

**Issue by tautology0** [ctxis/crackerjack#32]
We're having a problem where it keeps on running hashcat -I in the background; which leads to them erroring that hashcat is already running and the device profiles being unset which causes them not to be used on a run.

I'm not certain why hashcat is trying to enumerate the device profiles all the time, IMO it should only really try this when it first started crackerjack. If it can't enumerate the device profiles it should follow what's in the database.

Example image off the hashcat -I sessions (I enabled debug out for them)
![image](https://github.com/ctxis/crackerjack/assets/3503697/70a82ce6-d6ca-4adf-bb3d-9b190c2d8800)

**Comment by tautology0** [comment]
It looks like this is also causing crackerjack to respond slowly, causing gunicorn to time out and a 502 to be returned. I had to increase the gunicorn timeout to 900 to even get stuff to respond.

**Comment by sadreck** [comment]
Hi,

Apologies for the delay, life keeps getting in the way!

Quite a few things to update on here:

1. This repo is no longer maintained, please raise any future tickets at https://github.com/sadreck/crackerjack
2. I've put this fix under branch `hotfix_profiles_and_more` at https://github.com/sadreck/crackerjack/tree/hotfix_profiles_and_more
3. Please update your origin, pull down the repo, and checkout the `hotfix_profiles_and_more` branch.
4. You'll need to restart the crackerjack service for the changes to take effect.

The way I fixed this was to run the device detection only when the admin is visiting the system config page to define profiles. In all other cases (because the manager class is passed around quite a lot), it will load the detected devices from the database. When you refresh the code, it will "force" the device detection when it doesn't find it in the database, and will start using that output from that point onwards (this will happen once).

Let me know if it worked.

Thanks,
Pavel

**Comment by tautology0** [comment]
I added the issue here as I could add it in your fork at the time. I will raise in the fork in future! Thanks for looking in to it!

**Comment by tautology0** [comment]
Just to note, I still can't raise issues in the fork; so will be raising here for now.

**Comment by tautology0** [comment]
Fixed in https://github.com/sadreck/crackerjack/tree/hotfix_profiles_and_more
